### ISSUE TITLE
老哥能不能发下你TV文件 TVBUS的播放器APP

### ISSUE THREAD

**Issue by rong2er** [CCKNBC/ccknbc#1]
TVBUS://3或者4开头的专用播放器 能发下吗！

**Comment by CCKNBC** [comment]
啊这

**Comment by CCKNBC** [comment]
> TVBUS://3或者4开头的专用播放器 能发下吗！

我没有很久没看了，竟然有人发现这个文件

**Comment by rong2er** [comment]
那不是3天前更新的吗？

**Comment by rong2er** [comment]
一般的TVBUS源 我用百川TVBUS版 能播，但TVBUS://3，4开头的源要母鸡专用壳APP
